### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by Aaaya26** [Aaaya26/furima-40221#21]
下記記載のアプリについて挙動の確認をお願いいたします。

## URL
https://furima-40221.onrender.com/

## Basic認証
　・ID　　　　　  　  　  ：admin
　・パスワード　　　　：1234678
## 出品者用
　・メールアドレス　　：aaa@sample
　・パスワード　　　　：aaa111
## 購入者用
　・メールアドレス　　：bbb@sample
　・パスワード　　　　：bbb111

**Comment by motomuun** [comment]
@Aaaya26 さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
**商品出品機能の確認**

- [ ] **販売手数料と販売利益は、小数点以下を切り捨てて表示すること**
販売手数料と利益の計算式をご確認ください。下記画像の場合、利益は500円になるかと思います。
<img width="614" alt="スクリーンショット 2024-01-25 16 51 22" src="https://github.com/Aaaya26/furima-40221/assets/65059944/589b9f85-a23c-45a9-899a-640c02fbd937">


- [ ] **入力された販売価格によって、販売手数料や販売利益が変わること(JavaScriptを使用して実装すること)**
エラーハンドリングによって出品ページに戻ると、販売手数料や販売利益が変わらなくなります。何度でも変わるように修正をお願いします。

**商品編集機能の確認**

- [ ] **ログイン状態の場合は、自身が出品した販売中商品の商品情報編集ページに遷移できること**
自身が出品した販売中商品の「商品の編集」ボタンを押すと、トップページに遷移します。編集ページに遷移できるように修正をお願いします。



修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by Aaaya26** [comment]
ご確認いただきありがとうございます！
ご指摘箇所の修正を行いましたので、
再度ご確認をお願いいたします。

**Comment by motomuun** [comment]
@Aaaya26 さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます。

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
